//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public string ID { get; set; }
        public string ACC { get; set; }
        public string PASS { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ACCROLE { get; set; }
    }
}
