
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tour.Model
{

using System;
    using System.Collections.Generic;
    
public partial class ACCOUNT
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ACCOUNT()
    {

        this.KHACHHANGs = new HashSet<KHACHHANG>();

        this.NHANVIENs = new HashSet<NHANVIEN>();

    }


    public string ID { get; set; }

    public string ACC { get; set; }

    public string PASS { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public string ACCROLE { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<KHACHHANG> KHACHHANGs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<NHANVIEN> NHANVIENs { get; set; }

}

}
