
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tour.Model
{

using System;
    using System.Collections.Generic;
    
public partial class CHIPHI
{

    public string ID { get; set; }

    public Nullable<decimal> PHIAN { get; set; }

    public Nullable<decimal> PHICHOI { get; set; }

    public Nullable<decimal> PHIKHAC { get; set; }

    public Nullable<decimal> TONG { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

}

}
