//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIADIEM
    {
        public string ID { get; set; }
        public string TEN { get; set; }
        public string IDTINH { get; set; }
        public string CHITIET { get; set; }
        public byte[] PICBI { get; set; }
    
        public virtual TINH TINH { get; set; }
    }
}
