
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tour.Model
{

using System;
    using System.Collections.Generic;
    
public partial class KHACHHANG
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public KHACHHANG()
    {

        this.VEs = new HashSet<VE>();

    }


    public string ID { get; set; }

    public string TENKH { get; set; }

    public string CMND { get; set; }

    public string DIACHI { get; set; }

    public string GIOITINH { get; set; }

    public string SDT { get; set; }

    public byte[] PICBI { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<bool> IsVIP { get; set; }

    public Nullable<decimal> SPENDING { get; set; }

    public string PRI { get; set; }

    public string MAIL { get; set; }

    public string IDACC { get; set; }



    public virtual ACCOUNT ACCOUNT { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VE> VEs { get; set; }

}

}
