//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGGER
    {
        public string ID { get; set; }
        public string MESSAGE { get; set; }
        public string EMPLOYEEID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
