
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tour.Model
{

using System;
    using System.Collections.Generic;
    
public partial class NHANVIEN
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public NHANVIEN()
    {

        this.tb_NHIEMVU = new HashSet<tb_NHIEMVU>();

        this.tb_PHUTRACH = new HashSet<tb_PHUTRACH>();

    }


    public string ID { get; set; }

    public string MAIL { get; set; }

    public string SDT { get; set; }

    public byte[] PICBI { get; set; }

    public string TEN { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<bool> isAvailable { get; set; }

    public Nullable<int> SLDI { get; set; }

    public string IDACC { get; set; }



    public virtual ACCOUNT ACCOUNT { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tb_NHIEMVU> tb_NHIEMVU { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tb_PHUTRACH> tb_PHUTRACH { get; set; }

}

}
