//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHUONGTIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHUONGTIEN()
        {
            this.tb_PHUONGTIEN = new HashSet<tb_PHUONGTIEN>();
        }
    
        public string ID { get; set; }
        public string TEN { get; set; }
        public byte[] PICBI { get; set; }
        public string LOAI { get; set; }
        public string IDTINH { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> GIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PHUONGTIEN> tb_PHUONGTIEN { get; set; }
        public virtual TINH TINH { get; set; }
    }
}
